language: node_js
node_js:
  - "6.9"

branches:
  only:
    - master

before_script:
  - npm install -g --silent firebase-tools
  - npm install -g --silent @angular/cli

script:
  - ng lint
  - ng build --prod --aot --no-progress

after_success:
  - firebase deploy --token $FIREBASE_TOKEN
cache:
  directories:
    - node_modules
